CREATE TABLE IF NOT EXISTS users(
    id INT NOT NULL UNIQUE PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    icon VARCHAR(300),
    admin BOOLEAN NOT NULL DEFAULT FALSE
);